@startuml
'https://plantuml.com/sequence-diagram

actor "Retailer" as client
participant "Retailer Website Page" as apiGateway
participant "AddProductActivity" as addProductActivity
database "DynamoDB" as dynamoDB

client -> apiGateway : Add Product Form
apiGateway -> addProductActivity : Add Product Request
addProductActivity -> dynamoDB : Save Product

@enduml