@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "CreateGuestActivity" as createGuestActivity

client -> apiGateway : Create Guest Request
apiGateway -> createGuestActivity : createGuestRequest
createGuestActivity -> createGuestActivity : Create customer object with only name and location
createGuestActivity --> apiGateway : return CreateGuestRequest data
apiGateway --> client : return response 200 with CreateGuestRequest data


@enduml