@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "CheckoutActivity" as checkoutActivity
participant "InventoryDao" as inventoryDao
participant "CustomerDAO" as customerDao
database "DynamoDB" as dynamoDB

client -> apiGateway : Checkout Form
alt if cart is empty
apiGateway -> client : return 400 response
else else continue
end
alt if user is not signed in
apiGateway -> checkoutActivity : List<Product>
else if the user is signed in
apiGateway -> checkoutActivity : List<Product> and Customer Id
end
checkoutActivity -> checkoutActivity : create new Order object
loop for each product in the cart
checkoutActivity -> inventoryDao : Product Id
inventoryDao -> dynamoDB : Product Id
dynamoDB --> inventoryDao : Product
inventoryDao --> checkoutActivity : Product
alt if item is out of stock
checkoutActivity --> apiGateway : throw OutStockException
apiGateway --> client : return 400 response with msg
else else item is in stock
checkoutActivity -> checkoutActivity : remove 1 from the quantity
checkoutActivity -> inventoryDao : Product
inventoryDao -> dynamoDB : Product with updated quantity
end
end
alt if user is signed in
checkoutActivity -> customerDao : customer id
customerDao -> dynamoDB : customer id
dynamoDB --> customerDao : Customer
customerDao --> checkoutActivity : Customer
checkoutActivity -> checkoutActivity : Add orderId to historyOrderIds
checkoutActivity -> customerDao : Customer with updated historyOrderIds
customerDao -> dynamoDB : Customer

else else create a new Guest
checkoutActivity -> checkoutActivity : Create new Guest
checkoutActivity -> checkoutActivity : Add location to Guest
end
checkoutActivity --> apiGateway : return customer info
apiGateway --> client : return 200 response with msg

@enduml