@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "CheckoutActivity" as checkoutActivity
participant "InventoryDao" as inventoryDao
participant "CustomerDAO" as customerDao
database "DynamoDB" as dynamoDB

client -> apiGateway : Checkout Form
alt if cart is empty
apiGateway -> client : return 400 response
else else continue
end
alt if user is not signed in
apiGateway -> checkoutActivity : List<Product>
else if the user is signed in
apiGateway -> checkoutActivity : List<Product> and Customer Id
end
checkoutActivity -> checkoutActivity : create new Order object
loop for each product in the cart
checkoutActivity -> inventoryDao : Product Id
inventoryDao -> dynamoDB : Product Id
dynamoDB --> inventoryDao : Product
inventoryDao --> checkoutActivity : Product
alt if item is out of stock
checkoutActivity --> apiGateway : throw OutStockException
apiGateway --> client : return 400 response with message
end
end

alt if user is signed in
checkoutActivity -> customerDao : customer id
customerDao -> dynamoDB : customer id
dynamoDB --> customerDao : Customer
customerDao --> checkoutActivity : Customer
checkoutActivity -> checkoutActivity : Add orderId to historyOrderIds
else else create a new Guest
checkoutActivity -> checkoutActivity : Create New Guest
end
'TODO - Finish this diagram
'TODO - Implement a way to -1 from each product quantity and update the dynamoDB
'TODO - Implement a way to check out whether you are a signed in or not
'TODO - discuss if checking out right now just adds the order to customer's the order history and reduces the quantity from a product
@enduml