@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "CreateCustomerActivity" as createCustomerActivity
participant "CustomerDAO" as customerDao
database "DynamoDB" as dynamoDB

title CreateCustomerAccountRequest

client -> apiGateway : Create Account Form
apiGateway -> createCustomerActivity : Create Account Request
createCustomerActivity -> customerDao : Check if Customer Exists
customerDao -> dynamoDB : Get Customer Request
alt if customer already exists
dynamoDB --> customerDao : Return Customer Data
customerDao --> createCustomerActivity : Customer Object
createCustomerActivity --> apiGateway : throw CustomerAlreadyExistsException
apiGateway --> client : return 400 response
else else continue
end
dynamoDB --> customerDao : Return No Customer Data
customerDao --> createCustomerActivity : Customer Doesn't Exist
createCustomerActivity -> customerDao : Create Customer Request
customerDao -> dynamoDB : Create Customer
dynamoDB --> customerDao : return 200 response
customerDao --> createCustomerActivity : return 200 response
createCustomerActivity --> apiGateway : return 200 response
apiGateway --> client : return 200 w/response message

@enduml