@startuml
'https://plantuml.com/sequence-diagram

actor "Retailer" as client
participant "Website Page" as apiGateway
participant "Get Inventory" as getInventoryActivity
database "DynamoDB" as dynamoDB

client -> apiGateway : Get Inventory Form
apiGateway -> getInventoryActivity : Get Inventory Request
getInventoryActivity -> dynamoDB : Load Inventory

dynamoDB -> getInventoryActivity : Inventory
getInventoryActivity -> apiGateway : List<Product>
apiGateway -> client : Present Inventory and Products
@enduml