@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "GetInventoryActivity" as getInventoryActivity
participant "InventoryDao" as inventoryDao
database "DynamoDB" as dynamoDB

title First Endpoint - Get Inventory Of Products

client -> apiGateway : Get Inventory Request
apiGateway -> getInventoryActivity : Get Inventory Request
getInventoryActivity -> inventoryDao : Get Inventory Request
inventoryDao -> dynamoDB : getInventory request
dynamoDB --> inventoryDao : return List<Product>
inventoryDao --> getInventoryActivity : return List<Product>
getInventoryActivity --> apiGateway : return GetInventoryResult data
apiGateway --> client : return 200 response with GetInventoryResult data
@enduml

Scan request docs: https://stackoverflow.com/questions/10450962/how-can-i-fetch-all-items-from-a-dynamodb-table-without-specifying-the-primary-k