@startuml
'https://plantuml.com/sequence-diagram

actor "Retailer" as client
participant "Website Page" as apiGateway
participant "GetProductActivity" as getProductActivity
database "DynamoDB" as dynamoDB

client -> apiGateway : Get Product Form
apiGateway -> getProductActivity : Get Product Request
getProductActivity -> dynamoDB : Load Product

dynamoDB -> getProductActivity : Product Item
getProductActivity -> apiGateway : Product Object
apiGateway -> client : Present Product Information

@enduml