@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "LoginActivity" as loginActivity
participant "CustomerDAO" as customerDao
database "DynamoDB" as dynamoDB

title LoginRequest

client -> apiGateway : Login Account Form
apiGateway -> loginActivity : Login Account Request
loginActivity -> customerDao : Check if Customer Exists
customerDao -> dynamoDB : Get Customer Request

alt if customer does not exist
dynamoDB --> customerDao : Return No Customer Data
customerDao --> loginActivity : Customer Doesn't Exist
loginActivity --> apiGateway : throw CustomerDoesNotExistsException
apiGateway --> client : return 400 response
else else continue
end
dynamoDB --> customerDao : Return Customer Data
customerDao --> loginActivity : Customer Object
loginActivity --> apiGateway : return 200 response with Customer Data
apiGateway --> client : return 200 response
@enduml