@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "GETCustomerByEmailRequest" as getCustomerByEmailRequest
participant "CustomerDAO" as customerDao
database "DynamoDB" as dynamoDB

title GETCustomerByEmailRequest

client -> apiGateway : GET CustomerByEmail Request
apiGateway -> getCustomerByEmailRequest : GET CustomerByEmail Request
getCustomerByEmailRequest -> customerDao : Check if Customer's email exists
customerDao -> dynamoDB : Get CustomerByEmail Request

alt if customer does not exist
dynamoDB --> customerDao : return no Customer data
customerDao --> getCustomerByEmailRequest : return null Customer
getCustomerByEmailRequest --> apiGateway : throw CustomerDoesNotExistException
apiGateway --> client : return 400 response
else else continue
end
dynamoDB --> customerDao : return Customer data
customerDao --> getCustomerByEmailRequest : return Customer object
alt if submitted password does not match saved password
getCustomerByEmailRequest --> apiGateway : throw PasswordDoesNotMatchException
apiGateway --> client : return 400 response
else else continue
end
getCustomerByEmailRequest --> apiGateway : return GETCustomersResult data
apiGateway --> client : return 200 response with GETCustomersResult

@enduml