@startuml
'https://plantuml.com/sequence-diagram

actor "Customer" as client
participant "Customer Website Page" as apiGateway
participant "GETCustomerRequest" as getCustomerRequest
participant "CustomerDAO" as customerDao
database "DynamoDB" as dynamoDB

title GETCustomersRequest

client -> apiGateway : GET Customer Request
apiGateway -> getCustomerRequest : GET Customer Request
getCustomerRequest -> customerDao : Check if Customer Exists
customerDao -> dynamoDB : Get Customer Request

alt if customer does not exist
dynamoDB --> customerDao : return No Customer data
customerDao --> getCustomerRequest : return null Customer
getCustomerRequest --> apiGateway : throw CustomerDoesNotExistException
apiGateway --> client : return 400 response
else else continue
end
dynamoDB --> customerDao : return Customer data
customerDao --> getCustomerRequest : return Customer object
getCustomerRequest --> apiGateway : return GETCustomerResult data
apiGateway --> client : return 200 response with GETCustomerResult
@enduml